
import React from 'react';
import { LayoutDashboard, Factory, Box, ClipboardList, ShieldAlert, MessageSquare, HelpCircle, Users } from 'lucide-react';

export const FACILITIES = [
  { id: 'F01', name: 'P-51 FPSO', type: 'FPSO', coordinates: [-22.5, -40.5] as [number, number], status: 'Online' },
  { id: 'F02', name: 'P-40 Fixed', type: 'Fixed', coordinates: [-23.1, -41.2] as [number, number], status: 'Online' },
  { id: 'F03', name: 'Macae Terminal', type: 'Onshore', coordinates: [-22.37, -41.78] as [number, number], status: 'Maintenance' },
] as const;

export const MOC_STATUS_COLORS: Record<string, string> = {
  Draft: 'bg-gray-500/20 text-gray-400',
  Evaluation: 'bg-blue-500/20 text-blue-400',
  Approved: 'bg-emerald-500/20 text-emerald-400',
  Implementation: 'bg-orange-500/20 text-orange-400',
  Completed: 'bg-purple-500/20 text-purple-400',
};

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: <LayoutDashboard size={20} /> },
  { id: 'facilities', label: 'Facilities', icon: <Factory size={20} /> },
  { id: 'assets', label: 'Digital Twin', icon: <Box size={20} /> },
  { id: 'mocs', label: 'MOC Lifecycle', icon: <ClipboardList size={20} /> },
  { id: 'risk', label: 'Risk Matrix', icon: <ShieldAlert size={20} /> },
  { id: 'users', label: 'User Management', icon: <Users size={20} /> },
  { id: 'ai', label: 'AI Assistant', icon: <MessageSquare size={20} /> },
  { id: 'help', label: 'Help Center', icon: <HelpCircle size={20} /> },
];

export const TRANSLATIONS = {
  'en-US': {
    welcome: 'Welcome back, Chief Engineer',
    dashboard: 'Dashboard',
    facilities: 'Facility Network',
    assets: 'Asset Inventory',
    mocs: 'MOC Lifecycle',
    risk: 'Risk Analysis',
    users: 'User Management',
    ai: 'AI Engineering Advisor',
    help: 'Help Center',
    status: 'Status',
    priority: 'Priority',
    requester: 'Requester',
    actions: 'Actions',
    createNew: 'New MOC Request',
    technicalSummary: 'Technical Summary',
    askGemini: 'Ask Gemini Assistant...',
    signOut: 'Sign Out',
    activeMocs: 'Active MOCs',
    criticalRisks: 'Critical Risks',
    completed: 'Completed',
    systemHealth: 'System Health',
    changeTrends: 'Change Trends (2024)',
    workflowDist: 'Workflow Distribution',
    engMonitoring: 'Engineering Monitoring & Control System',
    governanceArchive: 'Governance Archive',
    fullTextSearch: 'Full-text search in Technical Dossier (ID, Title, Tag, Description)...',
    advancedFilters: 'Advanced Filters',
    workflowStatus: 'Workflow Status',
    priorityLevel: 'Priority Level',
    dateRange: 'Date Range',
    impactDimensions: 'Impact Dimensions',
    resetAll: 'Reset All Filters',
    refId: 'Ref ID',
    techDossier: 'Technical Dossier',
    unit: 'Unit',
    intervention: 'Intervention',
    noMatches: 'No matches found',
    adjustFilters: 'Try adjusting your filters or search terms.',
    techRiskMatrix: 'Technical Risk Matrix',
    quantAssessment: 'Quantitative assessment of probability vs impact severity.',
    exportPdf: 'Export PDF Report',
    probability: 'Probability (P)',
    severity: 'Severity (S)',
    assessmentDetails: 'Assessment Details',
    score: 'Score',
    extremeRisk: 'Extreme Risk',
    highRisk: 'High Risk',
    mediumRisk: 'Medium Risk',
    lowRisk: 'Low Risk',
    selectCell: 'Select a cell in the matrix to view detailed risk analysis.',
    govRule: 'Governance Rule',
    rule1: 'Score 15+: Requires HSE Director Approval',
    rule2: 'Score 8-14: Requires Technical Manager sign-off',
    aiAdvisorDesc: 'Powered by Gemini 3.0 Flash for technical intelligence.',
    aiOffline: 'Unable to reach technical advisor at this moment.',
    typeQuery: 'Type your engineering query...',
    generatingResponse: 'Generating Technical Response...',
    geospatialLogistics: 'Geospatial Logistics',
    realTimeAsset: 'Real-time asset positioning and status overlay.',
    allUnitsSecured: 'All Units Secured',
    operational: 'Operational',
    maintenance: 'Maintenance',
    terminalGateway: 'Terminal Gateway',
    clearanceRequest: 'Clearance Request',
    accessRecovery: 'Access Recovery',
    authorizedOnly: 'Authorized personnel only. Logs are maintained for audit compliance.',
    identifyRole: 'Identify your industrial role to request system clearance.',
    transmitRecovery: 'Transmit recovery token to your registered engineering mail.',
    engMail: 'Engineering Mail',
    accessKey: 'Access Key',
    keepAlive: 'Keep Session Alive',
    engageTerminal: 'Engage Terminal Access',
    newToMoc: 'New to MOC Studio?',
    requestClearance: 'Request Clearance',
    alreadyClearance: 'Already have clearance?',
    engageLogin: 'Engage Login',
    fullName: 'Full Name',
    provisionAccount: 'Provision Terminal Account',
    seniorEng: 'Senior Engineer',
    opsManager: 'Operations Manager',
    complianceAuditor: 'Compliance Auditor',
    safety: 'Safety',
    integrity: 'Integrity',
    techGovernance: 'Technical Governance',
    highIntegrity: 'High Integrity',
    safetyStandard: 'API RP 754 Compliant',
    integrityStandard: 'Role-Based Access',
    quickSwitch: 'Quick Switch clearance (Demo Mode)',
    brandMotto: 'Empowering engineers and compliance teams with a rigorous framework for industrial change management.',
    telemetry: 'Real-time Telemetry',
    technicalTags: 'Technical Tags',
    tagSearch: 'Search by Tag or Name...',
    lastMaintenance: 'Last Maintenance',
    temperature: 'Temperature',
    pressure: 'Pressure',
    flow: 'Flow',
    interventionHistory: 'Intervention History',
    sensorData: 'Live Sensor Diagnostics',
    tag: 'Tag',
    helpDesc: 'Knowledge base, technical standards, and engineering support.',
    knowledgeBase: 'Knowledge Base',
    gettingStarted: 'Getting Started',
    standardOper: 'Standard Operations',
    complianceReg: 'Compliance & Regulations',
    contactSupport: 'Contact Support',
    popularArticles: 'Popular Articles',
    viewAll: 'View All',
    searchHelp: 'Search for articles, standards, or procedures...',
    mocBasics: 'MOC Basics',
    riskMethod: 'Risk Matrix Methodology',
    auditTrail: 'Audit Trail Integrity',
    attachments: 'Supporting Documents',
    addAttachments: 'Add Attachments',
    dropFiles: 'Drop files here or click to upload',
    noAttachments: 'No supporting documents attached.',
    confirmReset: 'Confirm reset?',
    yes: 'Yes',
    no: 'No',
    changeType: 'Change Category',
    auditLog: 'Compliance Audit Log',
    taskTracker: 'Accountability & Tasks',
    runAssessment: 'Run AI Technical Assessment',
    submitApproval: 'Submit for Approval',
    approveChange: 'Approve MOC',
    implementChange: 'Start Implementation',
    verifyChange: 'Verify & Close',
    methodology: 'Methodology Explorer',
    standards: 'Regulatory Library',
    workflow: 'MOC Lifecycle Guide',
    tutorials: 'Video Tutorials',
    linkRisk: 'Vincular Avaliação de Risco',
    applyToMoc: 'Apply to this MOC',
    riskRationale: 'Risk Rationale',
    saveAssessment: 'Save Assessment',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No new notifications',
    clearAll: 'Clear all',
    userManagement: 'User Clearance & Registry',
    manageUsers: 'Personnel Governance',
    userRole: 'Clearance Role',
    email: 'Industrial Mail',
    name: 'Identity',
    status_active: 'Active',
    status_suspended: 'Suspended',
    discipline: 'Discipline',
    healthIndex: 'Health Index',
    liveSync: 'Live Sync',
    processParams: 'Process Parameters',
    technicalDossier: 'Technical Dossier',
    compositeRisk: 'Composite Risk Score',
    accountability: 'Accountability Matrix',
    provisionHub: 'Provision New Hub',
    commissionAsset: 'Commission Asset',
    purgeAsset: 'Purge Asset',
    assetDossier: 'Asset Dossier',
    emergencyProtocol: 'Emergency Protocol',
    initiateBypass: 'Initiate Bypass',
    techScope: 'Technical Scope',
    identityParams: 'Identity Parameters',
    riskAssessment: 'Risk Assessment',
    auditVerified: 'Chain Links Verified',
    markAs: 'Mark as',
    registryWarning: 'Registry Warning',
  },
  'pt-BR': {
    welcome: 'Bem-vindo, Engenheiro Chefe',
    dashboard: 'Painel',
    facilities: 'Rede de Instalações',
    assets: 'Inventário de Ativos',
    mocs: 'Ciclo de Vida MOC',
    risk: 'Análise de Risco',
    users: 'Gestão de Usuários',
    ai: 'Consultor de Engenharia IA',
    help: 'Central de Ajuda',
    status: 'Status',
    priority: 'Prioridade',
    requester: 'Solicitante',
    actions: 'Ações',
    createNew: 'Nova Solicitação MOC',
    technicalSummary: 'Resumo Técnico',
    askGemini: 'Pergunte ao Assistente Gemini...',
    signOut: 'Sair',
    activeMocs: 'MOCs Ativos',
    criticalRisks: 'Riscos Críticos',
    completed: 'Concluído',
    systemHealth: 'Saúde do Sistema',
    changeTrends: 'Tendências de Mudança (2024)',
    workflowDist: 'Distribuição de Fluxo',
    engMonitoring: 'Sistema de Monitoramento e Controle de Engenharia',
    governanceArchive: 'Arquivo de Governança',
    fullTextSearch: 'Busca textual no Dossier Técnico (ID, Título, Tag, Descrição)...',
    advancedFilters: 'Filtros Avançados',
    workflowStatus: 'Status do Fluxo',
    priorityLevel: 'Nível de Prioridade',
    dateRange: 'Intervalo de Datas',
    impactDimensions: 'Dimensões de Impacto',
    resetAll: 'Redefinir Filtros',
    refId: 'Ref ID',
    techDossier: 'Dossier Técnico',
    unit: 'Unidade',
    intervention: 'Intervenção',
    noMatches: 'Nenhum resultado encontrado',
    adjustFilters: 'Tente ajustar seus filtros ou termos de busca.',
    techRiskMatrix: 'Matriz de Risco Técnica',
    quantAssessment: 'Avaliação quantitativa de probabilidade vs severidade de impacto.',
    exportPdf: 'Exportar Relatório PDF',
    probability: 'Probabilidade (P)',
    severity: 'Severidade (S)',
    assessmentDetails: 'Detalhes da Avaliação',
    score: 'Pontuação',
    extremeRisk: 'Risco Extremo',
    highRisk: 'Risco Alto',
    mediumRisk: 'Risco Médio',
    lowRisk: 'Risco Baixo',
    selectCell: 'Selecione uma célula na matriz para ver a análise de risco detalhada.',
    govRule: 'Regra de Governança',
    rule1: 'Score 15+: Exige Aprovação do Diretor de SMS',
    rule2: 'Score 8-14: Exige assinatura do Gerente Técnico',
    aiAdvisorDesc: 'Alimentado por Gemini 3.0 Flash para inteligência técnica.',
    aiOffline: 'Não foi possível contatar o consultor técnico no momento.',
    typeQuery: 'Digite sua consulta de engenharia...',
    generatingResponse: 'Gerando Resposta Técnica...',
    geospatialLogistics: 'Logística Geoespacial',
    realTimeAsset: 'Posicionamento de ativos e sobreposição de status em tempo real.',
    allUnitsSecured: 'Todas Unidades Seguras',
    operational: 'Operacional',
    maintenance: 'Manutenção',
    terminalGateway: 'Gateway do Terminal',
    clearanceRequest: 'Pedido de Liberação',
    accessRecovery: 'Recuperação de Acesso',
    authorizedOnly: 'Apenas pessoal autorizado. Logs mantidos para conformidade de auditoria.',
    identifyRole: 'Identifique seu papel industrial para solicitar liberação no sistema.',
    transmitRecovery: 'Transmitir token de recuperação para seu e-mail de engenharia registrado.',
    engMail: 'E-mail de Engenharia',
    accessKey: 'Chave de Acesso',
    keepAlive: 'Manter Sessão Ativa',
    engageTerminal: 'Acessar Terminal',
    newToMoc: 'Novo no MOC Studio?',
    requestClearance: 'Solicitar Liberação',
    alreadyClearance: 'Já possui liberação?',
    engageLogin: 'Acessar Login',
    fullName: 'Nome Completo',
    provisionAccount: 'Provisionar Conta de Terminal',
    seniorEng: 'Engenheiro Sênior',
    opsManager: 'Gerente de Operações',
    complianceAuditor: 'Auditor de Conformidade',
    safety: 'Segurança',
    integrity: 'Integridade',
    techGovernance: 'Governança Técnica',
    highIntegrity: 'Alta Integridade',
    safetyStandard: 'Conformidade API RP 754',
    integrityStandard: 'Acesso Baseado em Papéis',
    quickSwitch: 'Troca rápida de liberação (Modo Demo)',
    brandMotto: 'Capacitando engenheiros e equipes de conformidade com um framework rigoroso para gestão de mudanças industriais.',
    telemetry: 'Telemetria em Tempo Real',
    technicalTags: 'Tags Técnicas',
    tagSearch: 'Buscar por Tag ou Nome...',
    lastMaintenance: 'Última Manutenção',
    temperature: 'Temperatura',
    pressure: 'Pressão',
    flow: 'Vazão',
    interventionHistory: 'Intervenções Histórico',
    sensorData: 'Diagnóstico de Sensores ao Vivo',
    tag: 'Tag',
    helpDesc: 'Base de conhecimento, normas técnicas e suporte de engenharia.',
    knowledgeBase: 'Base de Conhecimento',
    gettingStarted: 'Primeiros Passos',
    standardOper: 'Operações Padrão',
    complianceReg: 'Conformidade e Normas',
    contactSupport: 'Falar com Suporte',
    popularArticles: 'Artigos Populares',
    viewAll: 'Ver Tudo',
    searchHelp: 'Buscar por artigos, normas ou procedimentos...',
    mocBasics: 'Fundamentos de MOC',
    riskMethod: 'Metodologia da Matriz de Risco',
    auditTrail: 'Integridade da Trilha de Auditoria',
    attachments: 'Documentos de Suporte',
    addAttachments: 'Adicionar Anexos',
    dropFiles: 'Arraste os arquivos aqui ou clique para fazer upload',
    noAttachments: 'Nenhum documento de suporte anexado.',
    confirmReset: 'Confirmar reset?',
    yes: 'Sim',
    no: 'Não',
    changeType: 'Categoria da Mudança',
    auditLog: 'Log de Auditoria de Conformidade',
    taskTracker: 'Responsabilidade e Tarefas',
    runAssessment: 'Executar Avaliação Técnica IA',
    submitApproval: 'Enviar para Aprovação',
    approveChange: 'Aprovar MOC',
    implementChange: 'Iniciar Implementação',
    verifyChange: 'Verificar e Encerrar',
    methodology: 'Explorador de Metodologia',
    standards: 'Biblioteca Regulatória',
    workflow: 'Guia do Ciclo MOC',
    tutorials: 'Tutoriais em Vídeo',
    linkRisk: 'Vincular Avaliação de Risco',
    applyToMoc: 'Aplicar a este MOC',
    riskRationale: 'Justificativa de Risco',
    saveAssessment: 'Salvar Avaliação',
    notifications: 'Notificações',
    markAllRead: 'Marcar tudo como lido',
    noNotifications: 'Sem novas notificações',
    clearAll: 'Limpar tudo',
    userManagement: 'Liberação e Registro de Usuários',
    manageUsers: 'Governança de Pessoal',
    userRole: 'Papel de Liberação',
    email: 'E-mail Industrial',
    name: 'Identidade',
    status_active: 'Ativo',
    status_suspended: 'Suspenso',
    discipline: 'Disciplina',
    healthIndex: 'Índice de Saúde',
    liveSync: 'Sincronização ao Vivo',
    processParams: 'Parâmetros de Processo',
    technicalDossier: 'Dossier Técnico',
    compositeRisk: 'Pontuação de Risco Composta',
    accountability: 'Matriz de Responsabilidade',
    provisionHub: 'Provisionar Novo Hub',
    commissionAsset: 'Comissionar Ativo',
    purgeAsset: 'Expurgar Ativo',
    assetDossier: 'Dossier do Ativo',
    emergencyProtocol: 'Protocolo de Emergência',
    initiateBypass: 'Iniciar Bypass',
    techScope: 'Escopo Técnico',
    identityParams: 'Parâmetros de Identidade',
    riskAssessment: 'Avaliação de Risco',
    auditVerified: 'Elos da Cadeia Verificados',
    markAs: 'Marcar como',
    registryWarning: 'Aviso de Registro',
  }
};
